"""empty message

Revision ID: 166599b7c21b
Revises: d95cc12fa0d4
Create Date: 2021-05-13 23:16:26.505062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166599b7c21b'
down_revision = 'd95cc12fa0d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedido',
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=True),
    sa.Column('notaFiscal', sa.Integer(), nullable=True),
    sa.Column('dataPedido', sa.Date(), nullable=True),
    sa.Column('prazoPagamento', sa.Integer(), nullable=True),
    sa.Column('statusPagamento', sa.Boolean(), nullable=True),
    sa.Column('observacao', sa.String(length=500), nullable=True),
    sa.Column('id_empresa_funcionario', sa.Integer(), nullable=False),
    sa.Column('id_funcionario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_funcionario'], ['usuarioSistema.id'], ),
    sa.PrimaryKeyConstraint('id_pedido')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedido')
    # ### end Alembic commands ###
