"""empty message

Revision ID: 59b064df4a6c
Revises: 
Create Date: 2021-03-28 01:09:30.549335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b064df4a6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('sexo', sa.String(length=1), nullable=True),
    sa.Column('salario', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarioSistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('cidade', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('tipoUsuario', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarioSistema')
    op.drop_table('pessoas')
    # ### end Alembic commands ###
