"""empty message

Revision ID: 680ab1d11942
Revises: 
Create Date: 2021-05-01 13:18:11.646275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680ab1d11942'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=True),
    sa.Column('cnpj', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('cidade', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id_empresa')
    )
    op.create_index(op.f('ix_empresa_cnpj'), 'empresa', ['cnpj'], unique=True)
    op.create_table('pessoas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('sexo', sa.String(length=1), nullable=True),
    sa.Column('salario', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('idProduto', sa.Integer(), nullable=False),
    sa.Column('notaFiscal', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.Integer(), nullable=False),
    sa.Column('razaoSocial', sa.String(length=250), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('dataEntrada', sa.Date(), nullable=True),
    sa.Column('valorkg', sa.Float(), nullable=True),
    sa.Column('kg', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('idProduto')
    )
    op.create_table('usuarioSistema',
    sa.Column('id_pessoa', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('cidade', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('tipoUsuario', sa.String(length=50), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id_empresa'], ),
    sa.PrimaryKeyConstraint('id_pessoa')
    )
    op.create_index(op.f('ix_usuarioSistema_cpf'), 'usuarioSistema', ['cpf'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarioSistema_cpf'), table_name='usuarioSistema')
    op.drop_table('usuarioSistema')
    op.drop_table('produto')
    op.drop_table('pessoas')
    op.drop_index(op.f('ix_empresa_cnpj'), table_name='empresa')
    op.drop_table('empresa')
    # ### end Alembic commands ###
