"""empty message

Revision ID: cdf9423c7fd3
Revises: 
Create Date: 2021-04-07 22:06:06.644479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf9423c7fd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('sexo', sa.String(length=1), nullable=True),
    sa.Column('salario', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('idProduto', sa.Integer(), nullable=False),
    sa.Column('notaFiscal', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.Integer(), nullable=False),
    sa.Column('razaoSocial', sa.String(length=250), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('dataEntrada', sa.DateTime(), nullable=True),
    sa.Column('saldo', sa.Float(), nullable=True),
    sa.Column('prazoPagamento', sa.Integer(), nullable=True),
    sa.Column('valorKg', sa.Float(), nullable=True),
    sa.Column('caixa', sa.Float(), nullable=True),
    sa.Column('sacos', sa.Integer(), nullable=True),
    sa.Column('kg', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('idProduto')
    )
    op.create_table('usuarioSistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('cidade', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('tipoUsuario', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarioSistema')
    op.drop_table('produto')
    op.drop_table('pessoas')
    # ### end Alembic commands ###
