"""empty message

Revision ID: d4f4de3c8fdc
Revises: cdf9423c7fd3
Create Date: 2021-04-08 22:16:55.126254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f4de3c8fdc'
down_revision = 'cdf9423c7fd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('valorkg', sa.Float(), nullable=True))
    op.drop_column('produto', 'valorKg')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('valorKg', sa.FLOAT(), nullable=True))
    op.drop_column('produto', 'valorkg')
    # ### end Alembic commands ###
